### ISSUE TITLE
lag death?

### ISSUE THREAD

**Issue by unrealghostgamer** [mushroomhostage/exphc#27]
there was i sudden lag spike and when the game resumed i was dead and it says im dead till thursday?

**Comment by unrealghostgamer** [comment]
just looked u have death ban but isnt a 1 week ban a bit to long especially as it lagged maybe you should change it to a 30 minute ban

**Comment by mushroomhostage** [comment]
Sorry about the lag, it happens.. looking into it, seems the lag wasn't server-side however:

```
[04-12-2012 12:52:45] TPS: 20.0  Memory free: 5637.0/6077.0
Players online: 2
[04-12-2012 12:57:45] TPS: 20.0  Memory free: 5370.0/6077.0
Players online: 2
[04-12-2012 13:02:45] TPS: 20.0  Memory free: 5735.0/6077.0
Players online: 2
[04-12-2012 13:07:45] TPS: 20.0  Memory free: 5467.0/6077.0
Players online: 2
[04-12-2012 13:12:45] TPS: 20.0  Memory free: 5319.0/6077.0
Players online: 1
```

it has been running at full speed according to LagMeter/lag.log.. but granted the lag could have occurred between the samples, hard to tell. Another possibility is client-side or network-lag, I put together some steps here to investigate if you see lag again: https://github.com/mushroomhostage/exphc/wiki/Troubleshooting

As for the death ban, I see:

> hardcore info unrealghostgamer15:22:49 [INFO] [Hardcore] unrealghostgamer is ready to come back. They died on Thu Apr 12 13:12:09 CDT 2012 and could come back any time after Thu Apr 12 13:17:09 CDT 2012.

so you can come back :). Its only 5 minutes, originally I lowered it to this short amount for testing purposes but am finding out ultra-short death bans work pretty well (I had it at a week originally). The timestamp may be confusing however since it is in the server's timezone instead of your local timezone..

**Comment by unrealghostgamer** [comment]
oh thanks i have another friend who maybe interested IGN thomascooper

**Comment by mushroomhostage** [comment]
added
