### ISSUE TITLE
LCtrees++ don't work in client with new Forge... plz pm author of lct++

### ISSUE THREAD

**Issue by npdev453** [mushroomhostage/exphc#59]
https://github.com/cpw/FML/issues/34#issuecomment-6539514

**Comment by mushroomhostage** [comment]
Not yet a problem for the ExpHC server since its still on Forge 3.1.3.105 but will be an issue if the mods are updated (most significantly, IC^2 1.97 requires Forge 3.3.8). The author of Trees++ has been busy with school and moving but [said](http://www.minecraftforum.net/topic/1028159-125trees-v1335-forgesmpbukkit36-trees7-biomes/page__st__940#entry16106165) yesterday:

> Ok, I finished moving, and I finally got internet running into my new place, so I can start spending some time on updates. Just don't expect me to pump out updates like I use to XD 

I also PM'd him about the new leaf/log registry in Forge at https://github.com/MinecraftForge/MinecraftForge/pull/67 . Hopefully Trees++ will be updated soon :)

**Comment by mushroomhostage** [comment]
So I did an initial pass of all the mods on ExpHC, to plan their updates.. turns out Trees++ is one of the major blockers for updating:
https://github.com/mushroomhostage/exphc/wiki/Updating#Updating_to_1.2.5_Forge_3.3.x

**Comment by mushroomhostage** [comment]
Trees++ 1.3.36 is now out http://www.minecraftforum.net/topic/1028159-125trees-v1336-forgesmpbukkit36-trees7-biomes/page__st__960 with support for Forge 3.3. Client update only (have not yet tried it myself).

**Comment by mushroomhostage** [comment]
Ported official Trees++ 1.3.36 server, working with Forge 3.3.8.152.
Posted at http://mcportcentral.co.za/wiki/index.php?title=Ports_for_1.2.5
