### ISSUE TITLE
Hot air balloon and the world edge

### ISSUE THREAD

**Issue by overclock22** [mushroomhostage/exphc#73]
If you're traveling in  hot air balloon and you reach the world edge the teleport doesn't go well at all. 

The world seems to stop loading at least it did for me and the hot air balloon doesn't make it with you, though you still sit like you're in one. The world loads up correctly if you reconnect but the balloon is 100% lost. 

Don't know if this is something you can fix as its a mod conflict but it was an awkward experience.

**Comment by mushroomhostage** [comment]
Well.. the world edge is a strange place, with a powerful yet somewhat dangerous force to teleport you to the opposite edge. I like to think of them as similar to the Bermuda Triangle, where vessels are mysteriously lost.. 

But there may be something I can do about this, will update this post if I find out, since I'm curious myself why vehicles at the world boundaries behave this way. I'm just using WorldBorder with a knockback set to the world size, and it's supposed to handle boats correctly according to the author, at least with small knockbacks. May be a problem with being knocked back into unloaded chunks. Other vehicles from mods experience the same problem (THX Helicopter, and AnimalBikes (when it was in service)).

**Comment by overclock22** [comment]
Animal bikes looks like it was a crazy mod. 

Its no sweat about the world edge, i just wasnt sure if you were aware. Its just fortunate that it was only a balloon.

You see 1.3?! Going to be a while before that eh?

**Comment by mushroomhostage** [comment]
Yeah AnimalBikes was insane.. it was a really fun mod, lots of different bikes you could ride, but had some serious downsides - the bikes were infinite, had no cost to use, never wore out, and fairly cheap to make. A couple of the bikes could fly (very fast, too), so over time, most everyone had flying bikes and was using them extensively, causing excessive strain on the server to keep loading new chunks. Sad to see it go, but also glad to not have to deal with these disadvantages. Liking the Gravitation Suite much better.

For planned updates, I put notes on everything here: https://github.com/mushroomhostage/exphc/wiki/Updating

As for this reported issue with losing vehicles after the world edge, I'm still curious why this happens, have not had a chance to look into it. But I think I'm going to leave it like this for now, though it could be considered a bug I'm going to call it a feature :)
