### ISSUE TITLE
Thermal Expansion sawmill should be able to cut Trees++ logs

### ISSUE THREAD

**Issue by overclock22** [mushroomhostage/exphc#75]
Not sure if its been mentioned but the thermal expansion stuff doesn't appear to be working, unless I am just unfamiliar with it. 

I powered a sawmill with both a steam engine and the forestry electrical one. It goes on to store energy in both cases but it doesn't start to cut anything. Ive tried turning it on with lever and redstone, etc and nothing. 

The tabs for config and to show its being powered do not show up either but it does store mj.  

Hopefully its just me forgetting something basic but I believe it should work

O and no sticky pistons on machines makes me sad :C

**Comment by mushroomhostage** [comment]
What block ID + data value are you trying to cut?

**Comment by overclock22** [comment]
Ah It must be the logs I was trying to cut, they looked vanilla when i cut them down. It chops up some of the items you can mill with it though. 

The config and mj usage tabs still do not show up though but its no big deal as you can change the stuff with the wrench.

Figured it was me being a noob. 

I guess this is closed unless you think the tabs should be showing up.

**Comment by mushroomhostage** [comment]
Well, for some reason Trees++ creates log blocks with id 17 and metadata beyond the vanilla [range of 0-3](http://www.minecraftwiki.net/wiki/Data_values#Wood). It actually registers crafting recipes for data values 4-7 on the vanilla wood block. 

Someone else hit this issue [also](http://www.mcportcentral.co.za/index.php?topic=1875.msg19429#msg19429). It is confusing; the wood looks very similar to standard wood, but is not completely interchangeable..on a server with Trees++, I think you should be able to use its logs in a sawmill :)

Repurposing this bug for adding Trees++ logs to Thermal Expansion. 

Added in:
https://github.com/mushroomhostage/ExphcTweaks/commit/94ee1139b09b08343eceb7e9fb605c05a540a175 Use custom planks in sawmill recipes

Custom logs (including 17:5+, and the other custom logs like Crystal and Bukkit Tree) should now work in the Sawmill, as expected. Deployed with 1.2.5rev5. Any trouble with this change, let me know :)

Also, note that the server has been updated so you'll have to repeat step #1 of the setup instructions to update to the latest mods (otherwise you'll get an error connecting). Secondly, after the update you'll need to break any of your Thermal Expansion machines and place them again, in order for them to work after the update (Thermal Expansion from 1.0.2.1 to 1.0.4.1), among others.
