### ISSUE TITLE
Weird Connection lost issue? (login servers down)

### ISSUE THREAD

**Issue by XxXSilenozXxX** [mushroomhostage/exphc#86]
well i get this weird "http response code 503 URL: http://session.minecraft.net/game/joinserver..jsp?user=XxXSilenozXxX&sessionid=-115733504235167640&serverId=-2eed5aeced6fadc6" any thoughts on why i get this?

**Comment by mushroomhostage** [comment]
This happens when Mojang's login or session servers are down. The server tries to authenticate your login but is unable. 

You can see the status here: http://xpaw.ru/mcstatus/ - looks like the servers are back up now, should be able to login again (I just tested and am able to).

Unfortunately, not much I can do about Mojang's server outages. One possibility is running in "offline" mode so logins are not authenticated with their (unreliable) login/session servers. But this brings new problems, and requires a new authentication system on the server, and also has negative connotations (offline servers are often known as "cracked" servers, since they allow people to play without having purchased Minecraft, not something I want to support), and possible security risks. 

However, the login servers are only hit when you initially login, so one way to defend yourself against this outage as a player is to stay logged in all the time :) (at least, until the server restarts). But this has downsides too, someone might attack you while you're afk.. there's not really a good solution. The real fix has to come on Mojang's side, they have to fix their servers.

But it looks like they're up again now, so you should be able to login, for now..

**Comment by XxXSilenozXxX** [comment]
Thanks and yeah :/ seems to happen at a specific time at night but eh after awhile it gets fixed well hopefully mojang steps it up with those  types of things well thanks
