### ISSUE TITLE
Inverse creeper and bedrock

### ISSUE THREAD

**Issue by cpypcy** [mushroomhostage/exphc#92]
Is it intended that inverse creeper introduce you to void and bedrock misplacement?

**Comment by mushroomhostage** [comment]
Yes that's how it is designed at least.. probably the most dangerous Elemental Creeper of them all ;)

**Comment by overclock22** [comment]
Talking about inverse creepers one just detonated in my base and duped a whole bunch of stuff.

**Comment by mushroomhostage** [comment]
Weird, duped how? Blocks duped, or items in chests? I've noticed odd behavior with reverse creepers and tile entities. I had one detonate by a mob spawner and it turned it into a pig spawner (lost tile entity?).

**Comment by overclock22** [comment]
I had a creeper sneak into my nuke and energy area as i was expanding and though I didnt see it explode it obviousle did. 

It "destroyed" my nuclear reactor as in it reversed it but it did a terrible job. It broke the reactor in the sense that it forced it to dump its contents but it would up making 4 extra reactor chambers. the 6 sided reactor was reduced to only chamber and 3 additions but on the floor were 7 extra chambers. It destroyed most of my internal components (just the heat dispersers of course, because those are fun to make) but created enough reactor chambers to create a whole new reactor chamber on top of what I had. 

It also duplicated some water strainers I had nearby a long with a whole bunch of glass fiber cable. It was annoying to reset the cobblestone and chamber to how I had it but Im now sitting on 4 extra chambers.

**Comment by mushroomhostage** [comment]
Consider it an unexpected bonus :). Sometimes the creepers can have positive effects (like the cookie creeper), not seeing much potential for excessively abusing this interesting behavior of the reverse creepers (they spawn only rarely only randomly, not easily automated, cannot be captured with Sword + Silk Touch, no 'reverse creeper spawner' boxes, etc.), so they might duplicate certain items, or turn monster spawners into animal spawners, but they're also extremely dangerous and can trap you in bedrock or below the world. One of the few threats effective against the heavily-armed player (with quantum armor and such). Going to leave it like this for now.
