### ISSUE TITLE
Cool weather plugin suggestion

### ISSUE THREAD

**Issue by cpypcy** [mushroomhostage/exphc#93]
http://dev.bukkit.org/server-mods/weatherscopes/

In short: It create location based weather! Not a world wide single weather! Dynamic weather and much mor (from what i heard)

Main Features

It replaces the old weather system and allows you to create storms for every single world. You can set up

```
Location
Movement Speed
Intensity
Size
Duration 
```

for every Storm - or just add random storms with variable parameters.

```
WeatherScopes disables most other weather control plugin
Storms are treated as circles around their origin - not as rectangles 
```

**Comment by overclock22** [comment]
I like this idea

**Comment by mushroomhostage** [comment]
This does look pretty cool, always found it suboptimal how weather was global, local weather would be much nicer. Will have to try this out.

**Comment by cpypcy** [comment]
Have you tried it? On test server or something? How is it?

**Comment by mushroomhostage** [comment]
Haven't tried it yet

**Comment by mushroomhostage** [comment]
Installed this plugin on a test server, [WeatherScopes 1.3](http://dev.bukkit.org/server-mods/weatherscopes/files/4-weather-scopes-v1-3/). Though the server is still on 1.2.5, the plugin seems to load fine. Have not yet tested it much, but there are a couple concerns in running this plugin in production:
- Its fairly new, only 500 downloads. 
- "Known Bugs: may cause higher CPU usage" according to the author
- http://dev.bukkit.org/server-mods/weatherscopes/#c1 user reported a problem: "As it turns out, this seems to have hijacked the scheduler and locked up my server to the point I had to end task on it. No commands would process. My guess is that plugins that alter the time rate of the server to extend day or night are the culprit. Also, random storms seem to always cause nothing but thunder. No lightning, no clouds, no darkening, no rain. Just constant, uninterrupted thunder. Great idea, but maybe a bit more work is required?"

ExpHC has no other weather plugins installed so that should not be a problem, but I'm hesitant to add something which uses more CPU.. all the mods are already using plenty themselves.

**Comment by cpypcy** [comment]
As i said, it needs some testing, my non pvp server i play on has it and they run it just fine, they run quite lot of mods too, so i guess you configured it badly? From what i heard from players we have it the storms are epic and awesome, nothing bugged like you said. Use older version maybe?

**Comment by cpypcy** [comment]
Misclicked :D

**Comment by mushroomhostage** [comment]
Yeah its still a possibility. I haven't seen the issues mentioned above using the default config. Are you using 1.2 on your server?

**Comment by mushroomhostage** [comment]
Alright, I've put this plugin on the server, why not. Will see how it goes. Any trouble with it let me know..

**Comment by cpypcy** [comment]
Yeah we're on 1.2, but i play mostly here lately so i haven't seen weather myself only from what i heard from others. If CPU load get high you can probably remove it, and yeah we have a lot higher load since some people have huge factories tons of HV solars and still holding pretty decent.

**Comment by mushroomhostage** [comment]
Thanks, sounds like a plan. The plugin is live, and I've added a random storm, may remove it in the future if it causes too much lag but we'll see how it goes. Closing.
