### ISSUE TITLE
Enable at least armor smelting in alloy furnace?

### ISSUE THREAD

**Issue by cpypcy** [mushroomhostage/exphc#94]
Is there a way to smelt armor and weapons and maybe railroad tracks back to iron? If you don't want minecart exploit (mass fab + 4x HV solar is so OP dupe machine that this is just a joke with railcarts) Can't you just disable crafting minecarts from steel instead of disabling one of core abilities of that furnace?

Also side suggestion, is there a way to share locked safe with someone else? It's annoying to work in team and having lot of safes. Maybe way to lock golden and diamond chests only?

**Comment by mushroomhostage** [comment]
Alloy furnace reclaim recipes are mainly disabled to prevent the tin -> iron transmutation (craft bucket out of 3 x tin from IC2, smelt to 3 x iron), which could be exploited early game (before you have HV solar). 

Armor reclaiming was disabled along with it since RedPower only has one setting to disable all alloy furnace reclamation, "base.reclaimRecipes=0". But there may be something I can do about this.. I agree being able to smelt armor into ingots would be very useful.

**Comment by cpypcy** [comment]
What about weapons? I like to farm golden swords and iron swords from mobs at early game, not op and if you have some kind of farm it's easy too!

**Comment by mushroomhostage** [comment]
Would like to be able to smelt those too, yes. I think the only problematic alloy furnace reclaim recipes are minecarts and buckets.

**Comment by mushroomhostage** [comment]
Most alloy furnace recipes should be enabled now
