### ISSUE TITLE
NPE when interacting with Modular Forcefield

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#97]
When you right-click a forcefield, a harmless server error occurs:

```
20:29:10 [SEVERE] Could not pass event PlayerInteractEvent
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:467)
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:177)
        at net.minecraft.server.ItemInWorldManager.interact(ItemInWorldManager.java:292)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:635)
        at net.minecraft.server.Packet15Place.handle(SourceFile:39)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:251)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:106)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:82)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:569)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:457)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.NullPointerException
```

Reported in mffs_rev7 at http://forum.industrial-craft.net/index.php?page=Thread&postID=69237#post69237 , fixed in rev8+, just need to update.

**Comment by mushroomhostage** [comment]
From http://forum.industrial-craft.net/index.php?page=Thread&postID=69379#post69379:

"Rev8 changes - no gameplay changes, just a few bugfixes.
- Required clients to have the mod installed if the server does.
- Registered block properly on Bukkit.

Rev9 uploaded.
- Added inhibitor upgrade. Still unfinished and uncraftable. Only works on area projectors so far. Will cause freezes and out-of-memory crashes on large forcefields when they are activated, so you shouldn't use it yet! Prevents any forcefields from other cores activated after the inhibitor forcefield from working inside its area.
- Fixed players being able to crash the server with a ClassCastException (the reason this update is out before I finished the inhibitor upgrade)
- Removed a debug message
  "

**Comment by overclock22** [comment]
What are your thoughts on modifying the EU to shield point ratio.

**Comment by NewMilenium** [comment]
To answer overclock22, i think this is a bad idea. For a very simple reason : a forcefield has always a weakness.
The only possibility for someone to be almost totally safe is to NEVER get out of his forcefield - hence, he gets nothing from the outside and lives alone. And it's not totally safe, because there is still 1 way i won't tell here to access his base.
And if the forcefield user gets out of his base, the only possibility he has to activate again the forcefield once outside is wireless. And if he does that, the frequency can be found.
Not to mention there are others mistakes users of forcefield on this server keeps committing... :-)

**Comment by overclock22** [comment]
Should just update to the new modular force fields that have better identification systems and buffs for the shields. I mean I have a bunch of shields but Id gladly replace them for an id card so I could keep them up and just walk through. The wireless works but yeah leaves something to be desired. I don't know if its been ported though or what bugs would arise. 

As for the weaknesses of the current shield, they're silly. Anyone with a bunch of power systems doesn't have to leave the shield due to uu matter. O and if you're talking about using the walkie talkie to break into bases that's a lame thing that should be fixed @.@

I dont know, its just me perhaps. I was expecting a little more anarchy I guess. Maybe a little more post apocalyptic feel but I am still fairly new to the game. 

If the shields existed before the end of the world we're in; how did it destroy itself since nukes have no affect on shields XD

**Comment by NewMilenium** [comment]
I didn't understand everything in overclock22 comment, but i wanted to add something,

after several tests, i got at the moment 4 ways to break into a base which has forcefields protecting it. And I'm absolutely sure no one will think of all the 4 ways and so won't be able to fully protect his base.
I don't know what is overclock22 mentioning with a talkie-walkie, but if there's a bug with it, it should be explained to mushroomhostage so he can do something about it.

And as mushroomhostage mentionned somewhere, the feeling of not being safe is supposed to be constant on his server. This is survival. I got this feeling... not you? :-)

**Comment by overclock22** [comment]
I've felt overly safe for... well since I established a base that keeps creepers out. 

I find it disappointing, now I know this is a MC mod, that the way to defeat the shield is bullshit gimmicks that aren't obvious on the surface but after trawling google you would find the ways. It should be a damage vs shield point effect but its broken. To much shield per Eu and a lot of servers know this so they run it modded or not at all. 

It should be working to develop power systems that will keep it active not working out all the little gimmicks that people will use to slip past even the most well performing power system. I know you didn't write the mod but bleaagh makes me not want to even play.  

So here bullshit way number 5 since were going for bs instead of functionality, walk under a shield, have someone call you without having your phone out. The shield bubble is forced into a jukebox at the spot over you. Destroy jukebox and fly through the hole. Works on every bubble that isn't directly covered. If you have a efficiency pick thats high enough this doesn't even stop someone. 

I'm not sure what was so difficult to understand from my previous post, pretty straightforward. Theres no post apocalyptic survival its a walk in the park here if you don't have downs. I mean do not get me wrong in the slightest I love the mod picks and the way you got them to merge together so smoothly but its hardly post apocalyptic. There isn't even radiation to worry about anymore. Get a jetpack and trawl the water for plus signs and you'll be absolutely rich. Pvp doesn't exist because everyone locked away or invincible from other problems. 

Anyway I don't want you to think im griping on you or your choice in mods. It is your server and its hosted for free so I appreciate it buuutt I do think the shields and quantum chest plate ruin the pvp and survival feel.

**Comment by NewMilenium** [comment]
About your smartphone abuse > have 2 shields. Period.
Feel unsafe? Have 10 shields.

Not only i never googled about shields and I found out all I said by myself, but 2 of my techniques can go through any number of shields (it will take me a bit more time, though).

But from what you said, you will be happy if i find out your base. So, i see no problem.

edit : i mean, no problem with forcefield.

**Comment by mushroomhostage** [comment]
Updated mffs r10 with 1.2.5rev6

**Comment by mushroomhostage** [comment]
Created a new issue for possibly tweaking/changing MFFS further:

https://github.com/mushroomhostage/exphc/issues/100

Closing this issue since updated to mffs r10 in ExpHC 1.2.5rev6, which fixed the NPE on interaction.
